services:

  pgdb:
    image: postgres:15
    volumes:
      - postgres_ai_aura_test:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - migration
      - pgdb

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - pgdb

volumes:
  postgres_ai_aura_test: {}