# Generated by Django 5.1.2 on 2025-08-11 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Table's primary key.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Primary Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation timestamp.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record update timestamp.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.TextField(max_length=250)),
                (
                    "file_type",
                    models.TextField(
                        choices=[
                            ("pdf", "application/pdf"),
                            ("json", "application/json"),
                            (
                                "docx",
                                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            ),
                        ]
                    ),
                ),
                ("content", models.TextField()),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
