# Generated by Django 5.1.2 on 2025-08-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Table's primary key.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Primary Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation timestamp.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record update timestamp.",
                        verbose_name="Updated at",
                    ),
                ),
                ("category", models.TextField()),
                ("confidence_score", models.FloatField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="document_processing.document",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DocumentsClassifications",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
